services:
  audiomuse-ai-flask:
    image: ghcr.io/neptunehub/audiomuse-ai:dev
    build:
      context: ..
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
  audiomuse-ai-worker:
    image: ghcr.io/neptunehub/audiomuse-ai:dev
    build:
      context: ..
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
